# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#          LOCAL PRODUCTION-LIKE ENVIRONMENT          #
#                                                     #
# This file runs the application in production mode   #
# while building the image locally from source code.  #
# It is useful to validate a production-like setup    #
# on a local machine before deployment.               #
#                                                     #
# This setup keeps local DB and pgAdmin access for    #
# easier local testing and troubleshooting.            #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

name: eml-admintool-local-prod

networks:
  network:

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.build
    restart: unless-stopped
    networks:
      - network
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: 'production'
      BODY_SIZE_LIMIT: 'Infinity'
    volumes:
      - files:/app/files
      - env:/app/env
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:3000'
    depends_on:
      - dbs
  dbs:
    image: postgres:18.1
    restart: unless-stopped
    networks:
      - network
    environment:
      POSTGRES_USER: eml
      POSTGRES_PASSWORD: eml
      POSTGRES_DB: eml_admintool
    volumes:
      - database:/var/lib/postgresql
    ports:
      - '5432:5432'
  upd:
    image: ghcr.io/electron-minecraft-launcher/eml-admintool-updater:1.1.0
    restart: unless-stopped
    networks:
      - network
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./docker-compose.dev.yml:/app/compose/docker-compose.prod.yml
      - ./.env:/app/compose/.env:ro
      - env:/app/env:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
    labels:
      - com.eml.admintool.updater
  pga:
    image: dpage/pgadmin4
    networks:
      - network
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admintool@eml.com
      PGADMIN_DEFAULT_PASSWORD: eml
    ports:
      - '5050:80'
    depends_on:
      - dbs

volumes:
  database:
  files:
  env:
